// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Wb {
  Structure: Structure;
}

export interface Structure {
  "-common": string;
  "-compact": string;
  "-cross": string;
  "-generic": string;
  "-query": string;
  "-schemaLocation": string;
  "-structure": string;
  "-utility": string;
  "-xmlns": string;
  "-xsi": string;
  CodeLists: CodeLists;
  Concepts: Concepts;
  Header: Header;
  KeyFamilies: KeyFamilies;
}

export interface CodeLists {
  CodeList: KeyFamily[];
}

export interface KeyFamily {
  "-agencyID": ID;
  "-id": string;
  "-version": string;
  Code?: Code[];
  Name: DescriptionClass;
  Description?: DescriptionClass;
  Components?: Components;
}

export enum ID {
  Iaeg = "IAEG",
  Wb = "WB",
}

export interface Code {
  "-value": string;
  Description: DescriptionClass;
}

export interface DescriptionClass {
  "#text": string;
  "-lang": Lang;
}

export enum Lang {
  En = "en",
}

export interface Components {
  Attribute: Attribute;
  Dimension: Dimension[];
  PrimaryMeasure: PrimaryMeasure;
  TimeDimension: PrimaryMeasure;
}

export interface Attribute {
  "-assignmentStatus": string;
  "-attachmentLevel": string;
  "-codelist": string;
  "-conceptRef": string;
}

export interface Dimension {
  "-codelist": string;
  "-conceptRef": string;
  "-isFrequencyDimension"?: string;
}

export interface PrimaryMeasure {
  "-conceptRef": string;
}

export interface Concepts {
  Concept: KeyFamily[];
}

export interface Header {
  ID: string;
  Name: DescriptionClass;
  Prepared: string;
  Sender: Sender;
}

export interface Sender {
  "-id": ID;
  Contact: Contact;
  Name: DescriptionClass;
}

export interface Contact {
  Department: DescriptionClass;
  Email: string;
  Name: RoleClass;
  Role: RoleClass;
  Telephone: string;
}

export interface RoleClass {
  "-lang": Lang;
}

export interface KeyFamilies {
  KeyFamily: KeyFamily;
}
